<?php
/*
 * Add my new menu to the Admin Control Panel
 */


// Hook the 'admin_menu' action hook, run the function named 'mfp_Add_My_Admin_Link()'
add_action( 'admin_menu', 'addcode_Source_Print_Code' );


// Add a new top level menu link to the ACP
function addcode_Source_Print_Code()
{
  add_menu_page(
        'Add code source', // Title of the page
        'Code source', // Text to show on the menu link
        'manage_options', // Capability requirement to see the link
	'add-code-source',
        'test_init' // The 'slug' - file to display when clicking the link
    );
}


function test_init(){

  global $wpdb;
	$table_name = 'isir_'.$blog_id.'_code_source';
	$blog_id = get_current_blog_id();
	$result = $wpdb->get_results( "SELECT * FROM isir_".$blog_id."_code_source" );

  if($result != null)
  {
    echo '
    <h2>My projets : </h2>
    <div>
     Check the "is Favoris" box to add the projet to your favorites
   </div>
   <table id="tableVideo" cellpadding="10" cellspacing="10" class="tableau">
       <thead>
         <tr><th scope="col">Is favoris</th><th scope="col">Title</th><th scope="col">HTML URL</th><th scope="col"></th>
         </tr>
       </thead>
       <tbody>';
       foreach ( $result as $print )   {

         if($print->isFavoris == 0)
         {
           echo '<tr value="is Favoris"><th scope="row">
               <form id="myform" method="post">
                 <input class= "favoris" type="checkbox" id="'.$print->id.'" name="'.$print->id.'" onClick="this.form.submit();">
                 <input name="projectId" value="'.$print->id.'"  type="hidden"></input>
               </form>
             </th>';
         }else{
           echo '<tr value="is Favoris"><th scope="row">
                 <form id="myform" method="post">
                   <input type="checkbox" id="'.$print->id.'" name="'.$print->id.'" checked="true" onClick="this.form.submit();">
                   <input name="projectId" value="'.$print->id.'"  type="hidden"></input>
                 </form>
               </th>';
         }

       echo '
       <form method="POST" >
         <td>'.$print->name.'</td><td ><a href="'.$print->html_url.'">'.$print->html_url.'</a></td><td><button style = "background-color: #008CBA;  border: none; color: white; padding: 5px 5px; text-align: center; text-decoration: none; font-size: 16px; width : 100px; ">delete</button></td></tr>
         <input name="deleteProjectId" value="'.$print->id.'"  type="hidden"></input>
       </form>

         ';
        }

         echo '
       </tbody>
     </table>
   ';
  }



  echo '
 <h2>Search for the project that you want to add: </h2>
 <form method="POST">

 <fieldset id="group1" style="align:center; text-align:center; ">

    <div style=" margin-right:100px; margin-bottom:20px;  display:inline-block; ">
      <input type="radio" checked="checked" name="group1" value="project" >By project
    </div>

    <div style=" margin-right:100px; margin-bottom:20px; display:inline-block; ">
      <input type="radio"  name="group1" value="user" >By user
    </div>

  </fieldset>
   <div>
     Search Project keywords / Github user : <input type="search" id="q" name="q" placeholder="Enter Search Term" style="width:70%; ">
   </div>
   <input type="submit" value="Search" style="margin-left:35%; margin-top : 20px; width:20%; background-color: #008CBA;;  border: none; color: white; padding: 5px 5px; text-align: center; text-decoration: none; font-size: 16px;">
 </form>

  ';

  // This file is generated by Composer
require_once __DIR__ . '/vendor/autoload.php';


  if (isset($_POST['q'])  && isset($_POST['group1'])) {

    $radioVal = $_POST["group1"];
    $client = new \Github\Client();

    if($radioVal == "project")
    {

        $repositories = $client->api('search')->repositories($_POST['q']);
        echo '<h4> Select the project to add from the results of the research " '.$_POST['q'].' " : </h5>';
        foreach ($repositories['items'] as $value)
        {
          echo '

          <table style="background-color: white; margin: 30px; width : 90%; padding: 30px; ">
            <tr>
                <td  align="center" style="width : 25%; ">
                  <img  src="'.$value['owner']['avatar_url'].'" alt="Avatar" style="border-radius: 50%; width:70px;  height: 70px; display:inline-block; ">
                  <h4>'.$value['owner']['login'].'</h4>
                </td>
                <td style="position: relative; padding-left: 50px; width: 50%; ">
                  <h3 style=" margin-top: 0; ">'.$value['name'].'</h3>
                  ';
                  if($value['description'] != ""){
                    echo '<p style=" margin-top: 0; " >Description : '.$value['description'].'</p>';
                  }
                  echo '
                  <p style=" margin-top: 0; " >Created at  : '.$value['created_at'].' with last push at : '.$value['pushed_at'].'</p>
                  ';
                  if($value['language'] != ""){
                    echo '<p style=" margin-top: 0; " >Language  : '.$value['language'].'</p>';
                  }
                echo '
                <a  style="  margin-top: 0; " href="'.$value['html_url'].'">'.$value['html_url'].'</a>
                </td>
                <td  align="center"  style="width : 25%; ">
                  <form method="POST" >
                    <input name="name" value="'.$value['name'].'"  type="hidden"></input>
                    <input name="owner" value="'.$value['owner']['login'].'"  type="hidden"></input>
                    <input name="created_at" value="'.$value['created_at'].'"  type="hidden"></input>
                    <input name="avatar_url" value="'.$value['owner']['avatar_url'].'"  type="hidden"></input>
                    <input name="html_url" value="'.$value['html_url'].'"  type="hidden"></input>
                    <input name="clone_url" value="'.$value['clone_url'].'"  type="hidden"></input>
                    <input name="description" value="'.$value['description'].'"  type="hidden"></input>
                    <input name="language" value="'.$value['language'].'"  type="hidden"></input>
                    <input type="submit" value ="Add the project" style = "background-color: #008CBA;;  border: none; color: white; padding: 15px 32px; text-align: center; text-decoration: none; font-size: 16px;"></input>
                  </form>
                </td>
            </tr>
        </table>

          ';
        }
    }
    else if ($radioVal == "user")
    {

        $repositories = $client->api('users')->repositories($_POST['q']);
        echo '<h4> Select the project to add from the repositories of " '.$_POST['q'].' " : </h5>';

        foreach ($repositories as $value)
        {
          echo '

          <table style="background-color: white; margin: 30px; width : 90%; padding: 30px; ">
            <tr>
                <td  align="center" style="width : 25%; ">
                  <img  src="'.$value['owner']['avatar_url'].'" alt="Avatar" style="border-radius: 50%; width:70px;  height: 70px; display:inline-block; ">
                  <h4>'.$value['owner']['login'].'</h4>
                </td>
                <td style="position: relative; padding-left: 50px; width: 50%; ">
                  <h3 style=" margin-top: 0; ">'.$value['name'].'</h3>
                  ';
                  if($value['description'] != ""){
                    echo '<p style=" margin-top: 0; " >Description : '.$value['description'].'</p>';
                  }
                  echo '
                  <p style=" margin-top: 0; " >Created at  : '.$value['created_at'].' with last push at : '.$value['pushed_at'].'</p>
                  ';
                  if($value['language'] != ""){
                    echo '<p style=" margin-top: 0; " >Language  : '.$value['language'].'</p>';
                  }
                echo '
                <a  style="  margin-top: 0; " href="'.$value['html_url'].'">'.$value['html_url'].'</a>
                </td>
                <td  align="center"  style="width : 25%; ">
                  <form method="POST" >
                    <input name="name" value="'.$value['name'].'"  type="hidden"></input>
                    <input name="owner" value="'.$value['owner']['login'].'"  type="hidden"></input>
                    <input name="created_at" value="'.$value['created_at'].'"  type="hidden"></input>
                    <input name="html_url" value="'.$value['html_url'].'"  type="hidden"></input>
                    <input name="avatar_url" value="'.$value['owner']['avatar_url'].'"  type="hidden"></input>
                    <input name="clone_url" value="'.$value['clone_url'].'"  type="hidden"></input>
                    <input name="description" value="'.$value['description'].'"  type="hidden"></input>
                    <input name="language" value="'.$value['language'].'"  type="hidden"></input>
                    <input type="submit" value ="Add the project" style = "background-color: #008CBA;;  border: none; color: white; padding: 15px 32px; text-align: center; text-decoration: none; font-size: 16px;"></input>
                  </form>
                </td>
            </tr>
        </table>

          ';
      }
    }


  }




  if (isset($_POST['name']) )
  {
    global $wpdb;


    $name = $_POST['name'];
    $html_url = $_POST['html_url'];
    $clone_url = $_POST['clone_url'];
    $owner = $_POST['owner'];
    $created_at = $_POST['created_at'];
    $description = $_POST['description'];
    $language = $_POST['language'];
    $avatar_url = $_POST['avatar_url'];


    $today = date("Y-m-d H:i:s");

    $blog_id = get_current_blog_id();
    $table_name = 'isir_'.$blog_id.'_code_source';

    // echo $name.'</br>';
    // echo $html_url.'</br>';
    // echo $clone_url.'</br>';
    // echo $owner.'</br>';
    // echo $created_at.'</br>';
    // echo $description.'</br>';
    // echo $today.'</br>';
    // echo  $language.'</br>';
    // echo $avatar_url.'</br>';
    $wpdb->insert(
      $table_name,
      array(
        'name' => $name,
        'html_url' => $html_url,
        'clone_url' => $clone_url,
        'owner' => $owner,
        'created_at' => $created_at,
        'description' => $description,
        'addedAt' => $today,
        'language' => $language,
        'avatar_url' => $avatar_url,
        'isFavoris' => 0
      )
    );

    echo "<script type='text/javascript'>
          window.location=document.location.href;
          </script>";

  }

  if (isset($_POST['deleteProjectId']) )
  {

    global $wpdb;
    $blog_id = get_current_blog_id();
    $table_name = 'isir_'.$blog_id.'_code_source';


    $result = $wpdb->get_results( "DELETE FROM ".$table_name."  WHERE id=".$_POST['deleteProjectId']."");
    echo "<script type='text/javascript'>
      window.location=document.location.href;
      </script>";

  }

  if (isset($_POST['projectId']) )
{

	global $wpdb;
	$blog_id = get_current_blog_id();
	$table_name = 'isir_'.$blog_id.'_code_source';

	if(isset($_POST[$_POST['projectId']])){

		$result = $wpdb->get_results( "UPDATE ".$table_name." SET isFavoris = 1 WHERE id=".$_POST['projectId']."");
		echo "<script type='text/javascript'>
        window.location=document.location.href;
        </script>";

	}else{

		$result = $wpdb->get_results( "UPDATE ".$table_name." SET isFavoris = 0 WHERE id=".$_POST['projectId']."");
		echo "<script type='text/javascript'>
        window.location=document.location.href;
        </script>";
	}
}

}
